### ISSUE TITLE
Immutable data records

### ISSUE THREAD

**Issue by khornberg** [orbitjs/orbitjs-site#15]
You mention that the records are not stored in immutable data structures on https://github.com/orbitjs/orbitjs-site/edit/master/src/v0.15/guide/data-stores.md.

Is this left as a task for the user? Can this functionality be overwritten by users?

**Comment by tchak** [comment]
If you want your records sorted you can always add `.sort()` modifier to the query

**Comment by dgeb** [comment]
This repo has been archived and is now read-only. The current content for [orbitjs.com](https://orbitjs.com/) is maintained in the main [orbit](https://github.com/orbitjs/orbit/tree/main/website) repo.
